# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('code', models.CharField(blank=True, max_length=16, unique=True)),
                ('started_on', models.DateTimeField(null=True)),
                ('ended_on', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('I', 'In Progress'), ('C', 'Complete'), ('A', 'Assigned')], default='A', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQusetionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_feedbacks', to='feedback_manager.Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQusetionOptionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_qusetion_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fqom', to='feedback_manager.FeedbackQusetionMap')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_obtained', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=10)),
                ('question_type', models.CharField(choices=[('S', 'Subjective'), ('O', 'Objective'), ('C', 'Checkbox'), ('G', 'Grades')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='UserGradeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_grade_feedback', to='feedback_manager.Feedback')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.Grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedback_manager.Question'),
        ),
        migrations.AddField(
            model_name='feedbacktype',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='feedback_manager.Question'),
        ),
        migrations.AddField(
            model_name='feedbackqusetionoptionmap',
            name='submitted_option',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submited_option', to='feedback_manager.Option'),
        ),
        migrations.AddField(
            model_name='feedbackqusetionmap',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.Question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_manager.FeedbackType'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='questions',
            field=models.ManyToManyField(through='feedback_manager.FeedbackQusetionMap', to='feedback_manager.Question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
