# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_manager', '0002_auto_20170515_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrademap',
            name='feedback',
        ),
    ]
